project:
  type: website

website:
  title: "My Awesome {quarto-pyodide} Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

# Enable Pyodide on all post pages
filters:
  - pyodide
