project:
  type: website

website:
  title: "quarto-pyodide"
  reader-mode: true
  repo-url: https://github.com/coatless-quarto/pyodide
  repo-actions: [edit, issue]
  repo-subdir: "docs"
  google-analytics: "G-ZV56KS59C3"
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/coatless-quarto/pyodide/
    contents:
      - section: "Getting Started"
      - section: "Support"
        contents:
          - href: qpyodide-faq.qmd
            text: "Frequently Asked Questions"
          - href: https://github.com/coatless-quarto/pyodide/issues/new
            text: Submit an issue
      - section: "Demos"
        contents:
          - href: https://quarto.thecoatlessprofessor.com/pyodide/examples/readme/
            text: README Example
      - section: "Extra Information"
        contents:
          - href: qpyodide-release-notes.qmd
            text: Release Notes
          - href: qpyodide-acknowledgements.md
            text: Acknowledgements
          - href: https://quarto.thecoatlessprofessor.com/pyodide/tests/
            text: Test Suite

filters:
  - pyodide